num_epochs: 100
batch_size: 12

# vgg16(19)(_bn), resnet18(34, 50, 101, 152), densenet121(169, 161), inception_v3 
model: resnet101 
train_last: False

train:
    data: ../dataset/split/train/*.dcm
    phrase: train
    use_finetune: False
    model_path: checkpoint/best_resnet50.h5
    class:  &CLASS
        epidural: 0
        healthy: 1
        intraparenchymal: 2
        intraventricular: 3
        subarachnoid: 4
        subdural: 5

val:
    data: ../dataset/split/val/*.dcm
    phrase: val
    class:  *CLASS

test:
    data: ../dataset/test/*.dcm
    phrase: test
    model_path: checkpoint/best_resnet50.h5
    class: *CLASS

optimizer:
    # SGD, Adam, Adadelta
    name: SGD
    lr: 0.001

scheduler:
    step_size: 20
    gamma: 0.6       # become 0.5

